const MOUNTING_ELEMENT_ID = 'map-mount';

const MOUNTING_POINT = document.getElementById(MOUNTING_ELEMENT_ID);
const CZECH_REPUBLIC_LAT = 49.8175;
const CZECH_REPUBLIC_LONG = 15.473;
const DEFAULT_ZOOM = 5.5;
const CZECH_CENTER_BOUNDS = {
    lat: CZECH_REPUBLIC_LAT,
    lng: CZECH_REPUBLIC_LONG,
};
export {
    MOUNTING_POINT,
    DEFAULT_ZOOM,
    CZECH_CENTER_BOUNDS,
    CZECH_REPUBLIC_LAT,
    CZECH_REPUBLIC_LONG,
};
