# This workflow will run tests using node and then publish a package to npm registry when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node and .npmrc
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build-all
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node and .npmrc
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build-all
      - name: Set version to the release number
        run: npm version ${{ github.event.release.tag_name }}
      - name: Publish to npm registry
        run: npm publish --access public
      - name: Commit new version to package json
        uses: EndBug/add-and-commit@v4
        with:
          author_name: $GITHUB_ACTOR
          author_email: auto@commit.com
          message: "chore(npm): Automatic commit after publishing a new version"
          add: "package.json"
        env:
          NODE_AUTH_TOKEN: ${{secrets.temp_npm_token}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
